name = 'my-portfolio-cloud'

compatibility_date = "2026-01-10"
compatibility_flags = ["nodejs_compat"]

send_metrics = false

pages_build_output_dir = "./build/client"

[[kv_namespaces]]
binding = "MY_KV"
id = "7ec943eb53e54034b217f2bdce4a973d"